cmd/drone-autoscaler/main.go
config/config.go
config/load_test.go

I would like to avoid to add another sub domain "just" for the
autoscaler, with this config values it's possible to properly configure
the autoscaler to run on some specific root path, it defaults to / of
course.

Add configurable root path

---

cmd/drone-autoscaler/main.go
config/config.go
drivers/amazon/create.go
drivers/amazon/option.go
drivers/amazon/provider.go
drivers/digitalocean/create.go
drivers/digitalocean/option.go
drivers/digitalocean/provider.go
drivers/hetznercloud/create.go
drivers/hetznercloud/option.go
drivers/hetznercloud/provider.go
drivers/internal/scripts/userdata.go
drivers/internal/scripts/userdata_test.go

Currently the userdata is staticaly compiled in, with this change the
admin is able to customize the userdata or cloud-init content, the
content can be provided via path, base64 encoded string or a plain
string.

Make cloud-init/userdata configurable

---

engine/engine.go

small error discovered by testing the new pinger functionality - it falsely was using the collector, instead of the pinger.

Fix pinger

---

drivers/amazon/create.go
drivers/google/provider.go

… mainly Digitalocean used in other provider comments.
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

Fix some copy/pasta typo on providers

---

config/config.go
config/load_test.go
engine/planner.go
engine/planner_test.go
slack/slack.go
slack/slack_test.go

Now you can enable or disable slack notifications for specific types:
* create
* destroy
* error

 Make notifications configurable

---

cmd/drone-autoscaler/main.go
config/config.go
drivers/amazon/create.go
drivers/amazon/option.go
drivers/amazon/provider.go

feat(aws): add market type to allow usage of spot instances

---

cmd/drone-autoscaler/main.go

As reported here: https://discourse.drone.io/t/autoscaler-is-using-an-invalid-digital-ocean-image/3832, this fix the issue where `DRONE_DIGITALOCEAN_IMAGE` environment variable is ignored.

Fixed issue where the DRONE_DIGITALOCEAN_IMAGE environment variable would not be used.

---

config/load_test.go
drivers/digitalocean/create_test.go
drivers/digitalocean/option_test.go
drivers/digitalocean/provider.go
drivers/digitalocean/provider_test.go
server/servers_test.go

The `docker-16-04` image no longer exists on DigitalOcean, making the autoscaler to fail with the following message:
```
2019-02-20T12:48:40Z |ERRO| cannot create instance error="POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation." id=HxHZXzMLR03eUj25 image=docker-16-04 name=agent-9gyr9yxS region=nyc1 size=s-2vcpu-4gb
```
This PR updates the default image to `docker-18-04`.

Updated the default DigitalOcean image to use to 'docker-18-04'.

---

config/config.go
engine/engine.go
engine/install.go
engine/install_test.go

Today we encountered the issue with drone 1.0 agents, that they can not work with self-signed certificates on the drone server as we are not able to mount our ca.
This PR attempts to provide a environment variable in which one can define arbitrary host to agent-container mounts

allow host volume mounts for drone agents

---

.drone.yml
drivers/internal/userdata/userdata.go

This removes the hardcoded DNS override for the Docker daemon and instead uses the default Docker settings for how to retrieve DNS: https://docs.docker.com/config/containers/container-networking/
If Docker cannot retrieve the host DNS settings it defaults back to Google DNS so this should not be a breaking change. I have tested this with AWS and verified it uses the host DNS as expected.
Found this same DNS setting in the Digital Ocean userdata, but was not sure if you wanted to remove that since I have no way to test that provider. After looking over this file: https://github.com/drone/autoscaler/blob/master/drivers/digitalocean/userdata.go I was not sure why Digital Ocean had it's own userdata, the only difference appears to be not installing Docker. Let me know if you want me to update …

fix: removing hardcoded DNS settings

---

drivers/amazon/destroy.go
drivers/amazon/destroy_test.go
engine/reaper.go

Handling AWS instances not found when attempting to destroy. Implemented so that the reaper will clear out error'ed AWS instances.

Implemented ErrInstanceNotFound in AWS driver

---

Gopkg.lock
Gopkg.toml

To use zerolog 1.5.0 results in the logs, which have id multiple fields, like the following:
```
{"level":"debug","id":"Fhei0cWxDVBLgJeo","id":"UTtULrkDEak7TM25","id":"jVIK6lmsOeAbNWWU","id":"NNS0V6KlHzkUOdzc","time":"2019-06-14T19:02:56+09:00","message":"check capacity complete"}
```
I'd like to update zerolog to the latest version 1.14.3, which fixes this problem.

Update zerolog to fix that multiple id fields appear in logs

---

drivers/hetznercloud/create.go
drivers/hetznercloud/create_test.go
drivers/hetznercloud/provider.go
drivers/hetznercloud/provider_test.go

We are running quite often into an error like `we are unable to provision servers for this location, try with a different location or try later (resource_unavailable)`, the Hetzner Cloud support told me that we should be able to not provide any datacenter and Hetzner Cloud will automatically decide which datacenter could be taken for the new instance.
With this patch I have made the datacenter option optionally. With my
current tests it seems to be running fine as far as I can say.

Let Hetzner decide which datacenter to choose

---

engine/pinger.go

The server will still be in a running state after ping failure, and the autoscaler will keep trying to reprovision it. The stopped time is set, but the state is not updated. This puts it in a stopped state, similar to https://github.com/drone/autoscaler/blob/master/engine/collect.go#L108-L109 and https://github.com/drone/autoscaler/blob/master/engine/reaper.go#L121-L122

Failed to ping server fix

---

cmd/drone-autoscaler/main.go

I don't really know goloang, so I'm not sure if that's the only thing required for a fix, but it seems to be.
It has been brought up on June 3 in the chat already and never been fixed (although it is mentioned in the documentation as supported). I want to get the ball rolling on this issue.
> @bradrydzewski getting an unexpected error with the drone autoscaler:
> ```
> {"level":"fatal","error":"sql: unknown driver \"postgres\" (forgotten import?)","time":"2019-06-03T20:54:46Z","message":"Cannot establish database connection"}
> ```

Add postgresql driver to main.go

---

engine/install.go

When enabling the Garbage Collector for the agent, it is unable to create the container because the image is missing. I've added an image pull and fixed a typo in the function name.

Pull Garbage Collector image

---

engine/collect.go

I'm using the autoscaler with DigitalOcean.  The autoscaler went into a state where the server count was not reflecting the reality.  For example, when no Droplet existed on my account, the autoscaler was reporting something different:
```
9:12AM DBG check capacity id=Bjc93TuZjLNlUqoc max-pool=4 min-pool=0 pending-builds=0 running-builds=0 server-buffer=0 server-capacity=4 server-count=2
```
Attempting to remove these servers with the cli via `server destroy` command results with the following error on the autoscaler:
```
11:03AM DBG destroying server server=agent-p8clg4bK
11:03AM WRN cannot stop the agent error="Cannot connect to the Docker daemon at https://134.209.214.159:2376. Is the docker daemon running?" server=agent-p8clg4bK
11:03AM WRN droplet does not exist error="GET …
```

Fixed issue where an unexisting instance could not be destroyed.

---

config/config.go
config/load_test.go
engine/engine.go
engine/reaper.go

Currently an instance will be placed in an error state if there is no spot capacity available in AWS for example. These will count towards the autoscaler's capacity, and won't be destroyed until the reaper gets rid of them in the next hour. I moved the reaper interval to an environment variable so that one can choose the frequency.

Reaper interval environment variable

---

drivers/amazon/destroy.go

fix typo in amazon destroy log

---

drivers/hetznercloud/destroy.go
drivers/hetznercloud/destroy_test.go

Currently the Hetzner Cloud driver does not implement the
ErrInstanceNotFound error if a server does not exist anymore, I have
added a test and integrated the required functionality.

Implement ErrInstanceNotFound fir HetznerCloud

---

cmd/drone-autoscaler/main.go
config/config.go
drivers/google/create.go
drivers/google/option.go
drivers/google/provider.go

With existing code, GCP instances are not spawned if custom networks are specified for GCP instances. This PR is to add support for custom networks. Thx

support for custom networks in google cloud

---

cmd/drone-autoscaler/main.go
config/config.go
drivers/amazon/create.go
drivers/amazon/option.go
drivers/amazon/provider.go

This pull request implements configuring IOPS for AWS Provisioned IOPS EBS volumes (io1). 
Although autoscaler currently supports configuring EBS volume type with DRONE_AMAZON_VOLUME_TYPE, setting this parameter to `io1` causes agent creation to fail. This is because AWS requires that IOPS be set for `io1` volumes.
This PR adds a configuration `DRONE_AMAZON_VOLUME_IOPS` for configuring IOPS when using `io1` EBS volumes to fix failing agent creation.

Add Volume IOPS configuration for AWS io1 volumes

---

drivers/google/provider.go

This fixes an issue with GCP autoscalers not having the right scope/permission even with `Project Owner` role assigned to the service account.

[GCP] Insufficient scope fix

---

cmd/drone-autoscaler/main.go
config/config.go
config/load_test.go
drivers/google/create.go
drivers/google/option.go
drivers/google/option_test.go
drivers/google/provider.go

Hi All,
Attempting to add Google Private IP's as an option. Still learning go and not confident this is the correct way to approach the config. Happy to update as needed.

Adding an option to use a private IP with Google Cloud

---

config/config.go
config/load_test.go
drivers/google/option.go
drivers/google/option_test.go

The current SCOPES are not being applied because of a missing setup function.

Adds missing WithScopes function

---

cmd/drone-autoscaler/main.go
config/config.go
drivers/google/create.go
drivers/google/create_test.go
drivers/google/option.go
drivers/google/option_test.go
drivers/google/provider.go
provider.go

Adds option for passing an alternative GCP Service Account using the DRONE_GOOGLE_SERVICE_ACCOUNT_EMAIL env variable

Configure Service Account name for GCP instances

---

engine/docker.go

The `docker.NewClient` function is deprecated for `docker.NewClientWithOpts`. Specify the already present options but also use API negotiation rather than using the explicit default version.

Negotiate API Version

---

cmd/drone-autoscaler/main.go
drivers/google/create.go
provider.go
server/writer_test.go

Fix Scope variable not being passed on to the google provider

Fix scopes that were not being passed on to the Google provider

---

cmd/drone-autoscaler/main.go
config/config.go
config/load_test.go
drivers/openstack/create.go
drivers/openstack/create_test.go
drivers/openstack/destroy.go
drivers/openstack/destroy_test.go
drivers/openstack/option.go
drivers/openstack/option_test.go
drivers/openstack/provider.go
drivers/openstack/provider_test.go
drivers/openstack/testdata/flavorlistresp1.json

Without this PR it's not possible to launch agents without floating IPs on my OpenStack instance. Beside that it makes sense to support image and flavor selection by UUID.

Detect openstack ip without floating ips, add image and flavor by id

---

go.mod
go.sum
store/servers.go

* Makes retries more explicit by using terms like `retry` and `uncrecoverable`.
* Adds a backoff between retries to prevent hammering the service with requests, and allowing time for the service to recover.
* Adds randomness to the backoff, so that if we have multiple instances of this code running, it reduces the likelihood that they'll all retry requests at the same time (and again hammering the service).
* Changes attempts to `5` and adds a max backoff delay of 5s (with the new backoff, this will end up nearly equivalent time-wise to the current code)

Add retries with backoff and randomness

---

cmd/drone-autoscaler/main.go
config/config.go
config/load_test.go
drivers/google/create.go
drivers/google/option.go
drivers/google/option_test.go
drivers/google/provider.go
drivers/google/provider_test.go

This allows a user to pass a startup script instead of user data
For example `windows-startup-script-ps1`

Allow setting user data key for Google Cloud

---

config/config.go
engine/engine.go
engine/install.go

Allows to expose additional ports on the runner. Uses the normal parsing code from docker's SDK
Useful with https://github.com/drone-runners/drone-runner-docker/pull/15

Add configuration to expose ports

---

engine/install.go

Volumes are currently completely ignored

Fix: Allow volume mounts on Windows agents

---

drivers/google/provider.go

Fixes issue with commit: https://github.com/drone/autoscaler/commit/4547d562046ad38bd5d953238a9c916c5e0521da
context was removed from create & destroy but not GET

(bug) fixes issue where context is being used for waitGlobal operation

---

cmd/drone-autoscaler/main.go
config/config.go
config/load_test.go
drivers/amazon/create.go
drivers/amazon/option.go
drivers/amazon/option_test.go
drivers/amazon/provider.go
drivers/amazon/setup.go

When using more specialized instance types, it may happen that they aren't available in the given AZ
By giving multiple subnets, it allows the autoscaler to retry in a different AZ when that happens
I saw a TODO about using a small struct to track attempts. By adding that, I could extend the current sizeAlt behavior
The autoscaler will now try the regular size in all subnets, then the alternate size in all subnets
This is what the output looks like when combined with a size alt (2 invalid subnets + 1 invalid machine type):
```
{"attempt":1,"image":"ami-00149760ce42c967b","level":"debug","msg":"instance create","name":"drone-linux-aws-amd64-ZQumcEFd","region":"us-east-2","size":"blabla","subnet":"a","time":"2023-01-30T16:50:54Z"}
{"attempt":1,"error":"InvalidParameterValue: Invalid value …
```

AWS: Allow using a list of subnets

---

drivers/amazon/create.go

Before Tag change
After Tag change

fix: [CI-12899]: Added tag support for EBS volume
